from cProfile import label
from tkinter import*

win = Tk()
#win.geometry("900x300")
x = 30
border = 3
font = ("Arial", 9, "bold")
frame1 = Frame(win, borderwidth=border, width=600, height=x, relief='raised', background='red')
frame1.grid(row=0, column=0)
frame2 = Frame(win, borderwidth=border, width=300, height=x, relief='raised', background='orange')
frame2.grid(column=0, row=1)
frame3 = Frame(win, borderwidth=border, width=600, height=x, relief='raised', background='yellow')
frame3.grid(column=0, row=2)
frame4 = Frame(win, borderwidth=border, width=300, height=x, relief='raised', background='lime')
frame4.grid(column=0, row=3)
frame5 = Frame(win, borderwidth=border, width=600, height=x, relief='raised', background='deepskyblue')
frame5.grid(column=0, row=4)
frame6 = Frame(win, borderwidth=border, width=300, height=x, relief='raised', background='blue')
frame6.grid(column=0, row=5)
frame7 = Frame(win, borderwidth=border, width=600, height=x, relief='raised', background='violet')
frame7.grid(column=0, row=6)
label1 = Label(win, text="красный", bg="red", font=font)
label1.grid(column=0, row=0)
label2 = Label(win, text="оранжевый", bg="orange", font=font)
label2.grid(column=0, row=1)
label3 = Label(win, text="желтый", bg="yellow", font=font)
label3.grid(column=0, row=2)
label4 = Label(win, text="зеленый", bg="lime", font=font)
label4.grid(column=0, row=3)
label5 = Label(win, text="голубой", bg="deepskyblue", font=font)
label5.grid(column=0, row=4)
label6 = Label(win, text="синий", bg="blue", font=font)
label6.grid(column=0, row=5)
label7 = Label(win, text="фиолетовый", bg="violet", font=font)
label7.grid(column=0, row=6)
win.mainloop()